sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.10.109
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7vHeVSZNzeyJf8HmrX
    access-key-secret: ZsHYzIOjlfBcwWsZYDAmzjOdBWm79M
    bucket-name: cqwmpicture

